### ISSUE TITLE
Autofill shows TypeError in Chrome console.

### ISSUE THREAD

**Issue by subarachnid** [RobinHerbots/jquery.inputmask#2809]
When I use autofill to populate a value in an input mask field, the following error appears in the console:

`Uncaught TypeError: Cannot read properties of undefined (reading 'length')`

![image](https://github.com/user-attachments/assets/209d89bd-6171-47e6-89bb-20b4da5b13c6)

This error occurs because `event.key` is `undefined` in chrome when autofill is used, causing a failure in **eventhandlers.js**.
```js
var EventHandlers = {
    keyEvent: function (e, checkval, writeOut, strict, ndx) {
        const inputmask = this.inputmask,
            opts = inputmask.opts,
            $ = inputmask.dependencyLib,
            maskset = inputmask.maskset,
            input = this,
            $input = $(input),
            c = e.key, // <---------- e.key is undefined here

            // ...

        inputmask.ignorable =
            c.length > 1 && // <----------- Uncaught TypeError: Cannot read properties of undefined (reading 'length')
            !(input.tagName.toLowerCase() === "textarea" && c == keys.Enter);
```

- Browser: Chrome (official build) 127.0.6533.89 (64 bit)
- Inputmask version: 5.0.9-beta.62

**Comment by artbro-lad** [comment]
@RobinHerbots 
![photo_2024-12-02_18-16-42](https://github.com/user-attachments/assets/2d8f26af-dd94-4c4b-bdfb-cc152b327095)
https://codepen.io/ArtBro/pen/KwPprZq
The issue is fixed, but the mask doesn't work correctly when the value is autofilled.
When the value is inserted into the field through the browser's autocomplete suggestions, the mask doesn't apply correctly.
For example, if the field initially contains "100" and we select the suggested value "1000000", the result in the field will be "1000", and the thousand separator mask is not applied.

Thank you very much for your hard work on this library! It’s incredibly useful, and I really appreciate the effort you put into it.
